# Build Libssh (including all of its dependencies)

name: LibSSH

on:
  push:
    paths:
      - doc/**
      - .github/workflows/libssh.yml
  workflow_dispatch:

jobs:
  Build-VisualCxx:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
        toolset:
          - 14.3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Enable Developer Command Prompt
        # You may pin to the exact commit or the version.
        # uses: ilammy/msvc-dev-cmd@d8610e2b41c6d0f0c3b4c46dad8df0fd826c68e1
        uses: ilammy/msvc-dev-cmd@v1.10.0
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ matrix.toolset }}
          #sdk:   # use the latest
          #spectre: # set true to use VC libraries with sepctre mitigations
      - name: Get zlib
        run: |
          mkdir zlib
          cd zlib
          wget https://zlib.net/zlib-1.2.12.tar.gz -outfile zlib-1.2.12.tar.gz
          7z x zlib-1.2.12.tar.gz
          7z x zlib-1.2.12.tar
          ren zlib-1.2.12 1.2.12
        shell: powershell          
      - name: Build zlib
        shell: cmd
        run: |
          cd zlib\1.2.12
          cmake .
          nmake -f win32\Makefile.msc
